const TAG_TO_TOPIC: Record<string, { id: string; name: string }> = {
  algebra: { id: 'algebra', name: 'Algebra' },
  equations: { id: 'algebra', name: 'Algebra' },
  expansion: { id: 'algebra', name: 'Algebra' },
  factoring: { id: 'algebra', name: 'Algebra' },
  systems: { id: 'algebra', name: 'Algebra' },
  simplification: { id: 'algebra', name: 'Algebra' },
  quadratic: { id: 'algebra', name: 'Algebra' },
  inequalities: { id: 'algebra', name: 'Algebra' },
  linear: { id: 'algebra', name: 'Algebra' },
  percentages: { id: 'procent', name: 'Procent & Ekonomi' },
  percentage: { id: 'procent', name: 'Procent & Ekonomi' },
  'percentage-change': { id: 'procent', name: 'Procent & Ekonomi' },
  financial: { id: 'procent', name: 'Procent & Ekonomi' },
  compoundinterest: { id: 'procent', name: 'Procent & Ekonomi' },
  ratio: { id: 'procent', name: 'Procent & Ekonomi' },
  ratios: { id: 'procent', name: 'Procent & Ekonomi' },
  fractions: { id: 'procent', name: 'Procent & Ekonomi' },
  probability: { id: 'sannolikhet', name: 'Sannolikhet & Kombinatorik' },
  combinatorics: { id: 'sannolikhet', name: 'Sannolikhet & Kombinatorik' },
  conditionalprobability: { id: 'sannolikhet', name: 'Sannolikhet & Kombinatorik' },
  sets: { id: 'sannolikhet', name: 'Sannolikhet & Kombinatorik' },
  dice: { id: 'sannolikhet', name: 'Sannolikhet & Kombinatorik' },
  functions: { id: 'funktioner', name: 'Funktioner & Koordinatgeometri' },
  coordinategeometry: { id: 'funktioner', name: 'Funktioner & Koordinatgeometri' },
  linearfunctions: { id: 'funktioner', name: 'Funktioner & Koordinatgeometri' },
  exponential: { id: 'funktioner', name: 'Funktioner & Koordinatgeometri' },
  sequence: { id: 'funktioner', name: 'Funktioner & Koordinatgeometri' },
  sequences: { id: 'funktioner', name: 'Funktioner & Koordinatgeometri' },
  arithmetic: { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  numbertheory: { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  'number-theory': { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  divisibility: { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  primes: { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  'prime-numbers': { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  parity: { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  integers: { id: 'aritmetik', name: 'Aritmetik & Talteori' },
  powers: { id: 'potenser', name: 'Potenser & Rötter' },
  roots: { id: 'potenser', name: 'Potenser & Rötter' },
  exponent: { id: 'potenser', name: 'Potenser & Rötter' },
  squares: { id: 'potenser', name: 'Potenser & Rötter' },
  absolutevalue: { id: 'potenser', name: 'Potenser & Rötter' },
  statistics: { id: 'statistik', name: 'Statistik & Medelvärden' },
  mean: { id: 'statistik', name: 'Statistik & Medelvärden' },
  median: { id: 'statistik', name: 'Statistik & Medelvärden' },
  geometry: { id: 'geometri', name: 'Geometri & Mätning' },
  angles: { id: 'geometri', name: 'Geometri & Mätning' },
  triangle: { id: 'geometri', name: 'Geometri & Mätning' },
  area: { id: 'geometri', name: 'Geometri & Mätning' },
  perimeter: { id: 'geometri', name: 'Geometri & Mätning' },
  circle: { id: 'geometri', name: 'Geometri & Mätning' },
  rectangle: { id: 'geometri', name: 'Geometri & Mätning' },
  quadrilateral: { id: 'geometri', name: 'Geometri & Mätning' },
  pythagoras: { id: 'geometri', name: 'Geometri & Mätning' },
  pythagoreantheorem: { id: 'geometri', name: 'Geometri & Mätning' },
  Pythagoras: { id: 'geometri', name: 'Geometri & Mätning' },
  '3d-geometry': { id: '3d', name: '3D-geometri & Volymer' },
  volume: { id: '3d', name: '3D-geometri & Volymer' },
  'surface-area': { id: '3d', name: '3D-geometri & Volymer' },
  cone: { id: '3d', name: '3D-geometri & Volymer' },
  cylinder: { id: '3d', name: '3D-geometri & Volymer' },
  sphere: { id: '3d', name: '3D-geometri & Volymer' },
  cube: { id: '3d', name: '3D-geometri & Volymer' },
  prism: { id: '3d', name: '3D-geometri & Volymer' },
  logarithm: { id: 'logaritm', name: 'Logaritmer' },
  logarithmrules: { id: 'logaritm', name: 'Logaritmer' },
}

export function getTopicForQuestion(tags: string[]): { id: string; name: string } | null {
  for (const tag of tags) {
    if (TAG_TO_TOPIC[tag]) return TAG_TO_TOPIC[tag]
  }
  return null
}
